[package]
name = "voxer"
version = "0.1.0"
edition = "2024"

[features]
default = ["native"]
webgl = ["wgpu/webgl"]
webgpu = ["wgpu/webgpu"]
native = [
    "wgpu/dx12",
    "wgpu/metal",
    "wgpu/gles",
    "wgpu/vulkan"
]

[dependencies]
anyhow = "1.0.104"
wgpu = { version = "30.0.0", default-features = false, features = ["std", "parking_lot", "wgsl"] }
winit = "0.30.13"
bytemuck = { version = "1.25.1", features = ["derive"] }
dot_vox = { version = "5.2.0", default-features = false }
nalgebra = { version = "0.35.0", features = ["bytemuck"] }
egui = "0.35.0"
egui-wgpu = "0.35.0"
egui-winit = { version = "0.35.0", default-features = false, features = ["links", "wayland", "x11"] }
egui_plot = "0.36.0"
log = "0.4.33"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
pollster = "1.0.1"
env_logger = "0.11.11"

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2.126"
console_error_panic_hook = "0.1.7"
console_log = "1.1.0"
wasm-bindgen-futures = "0.4.76"
getrandom = { version = "0.4.3", features = ["wasm_js"] }

[build-dependencies]
nalgebra = { version = "0.35.0", features = ["bytemuck"] }
wesl = { version = "0.4.1", features = ["naga-ext"] }
wgsl_kiss = { path = "deps/wgsl_kiss" }

[patch.crates-io]
egui = { git = "https://github.com/emilk/egui.git", rev = "3fcadda5ba186c9a0f8c1546e2a3fefae6b1e863" }
egui-wgpu = { git = "https://github.com/emilk/egui.git", rev = "3fcadda5ba186c9a0f8c1546e2a3fefae6b1e863" }
egui-winit = { git = "https://github.com/emilk/egui.git", rev = "3fcadda5ba186c9a0f8c1546e2a3fefae6b1e863" }
emath = { git = "https://github.com/emilk/egui.git", rev = "3fcadda5ba186c9a0f8c1546e2a3fefae6b1e863" }
